// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Puluj.Analytics.Persistence;

#nullable disable

namespace Puluj.Analytics.Persistence.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    partial class AnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analytics")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Puluj.Analytics.Persistence.AnalysisRun", b =>
                {
                    b.Property<long>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RunId"));

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Instance")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("instance");

                    b.Property<int>("MessagesFingerprinted")
                        .HasColumnType("integer")
                        .HasColumnName("messages_fingerprinted");

                    b.Property<int>("MessagesScanned")
                        .HasColumnType("integer")
                        .HasColumnName("messages_scanned");

                    b.Property<int>("PairsFound")
                        .HasColumnType("integer")
                        .HasColumnName("pairs_found");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("WatermarkFrom")
                        .HasColumnType("bigint")
                        .HasColumnName("watermark_from");

                    b.Property<long>("WatermarkTo")
                        .HasColumnType("bigint")
                        .HasColumnName("watermark_to");

                    b.HasKey("RunId")
                        .HasName("pk_runs");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_runs_started_at");

                    b.ToTable("runs", "analytics");
                });

            modelBuilder.Entity("Puluj.Analytics.Persistence.AnalyticsState", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_state");

                    b.ToTable("state", "analytics");
                });

            modelBuilder.Entity("Puluj.Analytics.Persistence.MessageCopy", b =>
                {
                    b.Property<int>("CopySourceId")
                        .HasColumnType("integer")
                        .HasColumnName("copy_source_id");

                    b.Property<string>("CopyPostKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("copy_post_key");

                    b.Property<int>("OriginalSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("original_source_id");

                    b.Property<string>("OriginalPostKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("original_post_key");

                    b.Property<float>("Containment")
                        .HasColumnType("real")
                        .HasColumnName("containment");

                    b.Property<DateTimeOffset>("CopyPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("copy_published_at");

                    b.Property<long>("CopyRawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("copy_raw_message_id");

                    b.Property<double>("DelaySeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("delay_seconds");

                    b.Property<DateTimeOffset>("FoundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("found_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<float>("Jaccard")
                        .HasColumnType("real")
                        .HasColumnName("jaccard");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OriginalPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_published_at");

                    b.Property<long>("OriginalRawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("original_raw_message_id");

                    b.HasKey("CopySourceId", "CopyPostKey", "OriginalSourceId", "OriginalPostKey")
                        .HasName("pk_copies");

                    b.HasIndex("CopyPublishedAt")
                        .HasDatabaseName("ix_copies_copy_published_at");

                    b.HasIndex("OriginalRawMessageId")
                        .HasDatabaseName("ix_copies_original_raw_message_id");

                    b.HasIndex("CopySourceId", "OriginalSourceId", "CopyPublishedAt")
                        .HasDatabaseName("ix_copies_copy_source_id_original_source_id_copy_published_at");

                    b.ToTable("copies", "analytics");
                });

            modelBuilder.Entity("Puluj.Analytics.Persistence.MessageFingerprint", b =>
                {
                    b.Property<long>("RawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_message_id");

                    b.PrimitiveCollection<long[]>("Bands")
                        .HasColumnType("bigint[]")
                        .HasColumnName("bands");

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<bool>("ForwardedExternal")
                        .HasColumnType("boolean")
                        .HasColumnName("forwarded_external");

                    b.Property<string>("ForwardedFrom")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("forwarded_from");

                    b.Property<int?>("ForwardedSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("forwarded_source_id");

                    b.Property<DateTimeOffset>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.Property<bool>("IsEdit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edit");

                    b.Property<byte[]>("MinHash")
                        .HasColumnType("bytea")
                        .HasColumnName("min_hash");

                    b.Property<string>("PostKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("post_key");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("ShingleCount")
                        .HasColumnType("integer")
                        .HasColumnName("shingle_count");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<int>("TextLength")
                        .HasColumnType("integer")
                        .HasColumnName("text_length");

                    b.HasKey("RawMessageId")
                        .HasName("pk_messages");

                    b.HasIndex("Bands")
                        .HasDatabaseName("ix_messages_bands")
                        .HasFilter("bands IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Bands"), "gin");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_messages_published_at");

                    b.HasIndex("SourceId", "ChannelId")
                        .HasDatabaseName("ix_messages_source_id_channel_id");

                    b.HasIndex("SourceId", "PublishedAt")
                        .HasDatabaseName("ix_messages_source_id_published_at");

                    b.ToTable("messages", "analytics");
                });

            modelBuilder.Entity("Puluj.Analytics.Persistence.TrackFirst", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<int>("TargetCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("target_category_id");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_code");

                    b.Property<int>("Firsts")
                        .HasColumnType("integer")
                        .HasColumnName("firsts");

                    b.Property<int>("LagCount")
                        .HasColumnType("integer")
                        .HasColumnName("lag_count");

                    b.Property<double>("LagSecondsSum")
                        .HasColumnType("double precision")
                        .HasColumnName("lag_seconds_sum");

                    b.Property<int>("Participations")
                        .HasColumnType("integer")
                        .HasColumnName("participations");

                    b.HasKey("Day", "SourceId", "TargetCategoryId")
                        .HasName("pk_track_firsts");

                    b.ToTable("track_firsts", "analytics");
                });
#pragma warning restore 612, 618
        }
    }
}
