// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Puluj.Infrastructure.Persistence;

#nullable disable

namespace Puluj.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PulujDbContext))]
    [Migration("20260911032544_AddAppSettings")]
    partial class AddAppSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Puluj.Domain.Entities.AirAlert", b =>
                {
                    b.Property<long>("AirAlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("air_alert_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AirAlertId"));

                    b.Property<int>("AlertType")
                        .HasColumnType("integer")
                        .HasColumnName("alert_type");

                    b.Property<long?>("EndRawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("end_raw_message_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    b.Property<string>("SourceAlertId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_alert_id");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<long?>("StartRawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("start_raw_message_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("AirAlertId")
                        .HasName("pk_air_alerts");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_air_alerts_place_id")
                        .HasFilter("ended_at IS NULL");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_air_alerts_started_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("StartedAt"), "brin");

                    b.HasIndex("SourceId", "SourceAlertId")
                        .IsUnique()
                        .HasDatabaseName("ix_air_alerts_source_id_source_alert_id");

                    b.ToTable("air_alerts", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_app_settings");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.CollectorState", b =>
                {
                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<JsonDocument>("Cursor")
                        .HasColumnType("jsonb")
                        .HasColumnName("cursor");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<DateTimeOffset?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled_at");

                    b.Property<string>("LastSourceMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("last_source_message_id");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.HasKey("SourceId")
                        .HasName("pk_collector_states");

                    b.ToTable("collector_states", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.Observation", b =>
                {
                    b.Property<long>("ObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("observation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ObservationId"));

                    b.Property<int>("ClassificationConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("classification_confidence");

                    b.Property<int?>("DestinationPlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_place_id");

                    b.Property<int>("DirectionConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("direction_confidence");

                    b.Property<double?>("DirectionDeg")
                        .HasColumnType("double precision")
                        .HasColumnName("direction_deg");

                    b.Property<int>("DirectionKind")
                        .HasColumnType("integer")
                        .HasColumnName("direction_kind");

                    b.Property<long?>("DuplicateOfObservationId")
                        .HasColumnType("bigint")
                        .HasColumnName("duplicate_of_observation_id");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<int>("IdentificationMethod")
                        .HasColumnType("integer")
                        .HasColumnName("identification_method");

                    b.Property<string>("IdentificationSource")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("identification_source");

                    b.Property<Geometry>("Location")
                        .HasColumnType("geography (geometry, 4326)")
                        .HasColumnName("location");

                    b.Property<double?>("LocationAccuracyKm")
                        .HasColumnType("double precision")
                        .HasColumnName("location_accuracy_km");

                    b.Property<int>("LocationKind")
                        .HasColumnType("integer")
                        .HasColumnName("location_kind");

                    b.Property<int?>("LocationPlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("location_place_id");

                    b.Property<int>("ModelConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("model_confidence");

                    b.Property<int?>("ObjectCount")
                        .HasColumnType("integer")
                        .HasColumnName("object_count");

                    b.Property<bool>("ObjectCountIsApproximate")
                        .HasColumnType("boolean")
                        .HasColumnName("object_count_is_approximate");

                    b.Property<int>("ObservationConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("observation_confidence");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<int?>("OriginPlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("origin_place_id");

                    b.Property<JsonDocument>("ParserMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("parser_metadata");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("parser_version");

                    b.Property<long>("RawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_message_id");

                    b.Property<int>("SegmentIndex")
                        .HasColumnType("integer")
                        .HasColumnName("segment_index");

                    b.Property<string>("SegmentText")
                        .HasColumnType("text")
                        .HasColumnName("segment_text");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<int?>("ThreatCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("threat_category_id");

                    b.Property<int?>("ThreatClassId")
                        .HasColumnType("integer")
                        .HasColumnName("threat_class_id");

                    b.Property<int?>("ThreatFamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("threat_family_id");

                    b.Property<int?>("ThreatModelId")
                        .HasColumnType("integer")
                        .HasColumnName("threat_model_id");

                    b.HasKey("ObservationId")
                        .HasName("pk_observations");

                    b.HasIndex("DestinationPlaceId")
                        .HasDatabaseName("ix_observations_destination_place_id");

                    b.HasIndex("DuplicateOfObservationId")
                        .HasDatabaseName("ix_observations_duplicate_of_observation_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_observations_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("LocationPlaceId")
                        .HasDatabaseName("ix_observations_location_place_id");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("ix_observations_observed_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ObservedAt"), "brin");

                    b.HasIndex("OriginPlaceId")
                        .HasDatabaseName("ix_observations_origin_place_id");

                    b.HasIndex("RawMessageId")
                        .HasDatabaseName("ix_observations_raw_message_id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_observations_source_id");

                    b.HasIndex("ThreatCategoryId")
                        .HasDatabaseName("ix_observations_threat_category_id");

                    b.HasIndex("ThreatFamilyId")
                        .HasDatabaseName("ix_observations_threat_family_id");

                    b.HasIndex("ThreatModelId")
                        .HasDatabaseName("ix_observations_threat_model_id");

                    b.HasIndex("ThreatClassId", "ObservedAt")
                        .HasDatabaseName("ix_observations_threat_class_id_observed_at");

                    b.ToTable("observations", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.Place", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlaceId"));

                    b.Property<Point>("Centroid")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("centroid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_key");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry (geometry, 4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("KatottgCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("katottg_code");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string[]>("NameVariants")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("name_variants");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int?>("Population")
                        .HasColumnType("integer")
                        .HasColumnName("population");

                    b.Property<double>("RadiusKm")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_km");

                    b.HasKey("PlaceId")
                        .HasName("pk_places");

                    b.HasIndex("Centroid")
                        .HasDatabaseName("ix_places_centroid");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Centroid"), "gist");

                    b.HasIndex("ExternalKey")
                        .IsUnique()
                        .HasDatabaseName("ix_places_external_key");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_places_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("KatottgCode")
                        .IsUnique()
                        .HasDatabaseName("ix_places_katottg_code")
                        .HasFilter("katottg_code IS NOT NULL");

                    b.HasIndex("NameVariants")
                        .HasDatabaseName("ix_places_name_variants");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameVariants"), "gin");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_places_parent_id");

                    b.HasIndex("Level", "CountryCode")
                        .HasDatabaseName("ix_places_level_country_code");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ProcessingError", b =>
                {
                    b.Property<long>("ProcessingErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("processing_error_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProcessingErrorId"));

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<JsonDocument>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<long?>("RawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_message_id");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage");

                    b.HasKey("ProcessingErrorId")
                        .HasName("pk_processing_errors");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_processing_errors_occurred_at");

                    b.HasIndex("RawMessageId")
                        .HasDatabaseName("ix_processing_errors_raw_message_id");

                    b.ToTable("processing_errors", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.RawMessage", b =>
                {
                    b.Property<long>("RawMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("raw_message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RawMessageId"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("integer")
                        .HasColumnName("processing_status");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<JsonDocument>("RawPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceMessageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_message_id");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("RawMessageId")
                        .HasName("pk_raw_messages");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_raw_messages_hash");

                    b.HasIndex("ProcessingStatus")
                        .HasDatabaseName("ix_raw_messages_processing_status")
                        .HasFilter("processing_status = 0");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_raw_messages_published_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PublishedAt"), "brin");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_raw_messages_received_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ReceivedAt"), "brin");

                    b.HasIndex("SourceId", "SourceMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_raw_messages_source_id_source_message_id");

                    b.ToTable("raw_messages", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.Source", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SourceId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<JsonDocument>("Config")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<TimeSpan?>("PollingInterval")
                        .HasColumnType("interval")
                        .HasColumnName("polling_interval");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<double>("TrustLevel")
                        .HasColumnType("double precision")
                        .HasColumnName("trust_level");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("url");

                    b.HasKey("SourceId")
                        .HasName("pk_sources");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sources_code");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatCategory", b =>
                {
                    b.Property<int>("ThreatCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("threat_category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ThreatCategoryId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("ThreatCategoryId")
                        .HasName("pk_threat_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_threat_categories_code");

                    b.ToTable("threat_categories", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatClass", b =>
                {
                    b.Property<int>("ThreatClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("threat_class_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ThreatClassId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("ThreatCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("threat_category_id");

                    b.HasKey("ThreatClassId")
                        .HasName("pk_threat_classes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_threat_classes_code");

                    b.HasIndex("ThreatCategoryId")
                        .HasDatabaseName("ix_threat_classes_threat_category_id");

                    b.ToTable("threat_classes", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatFamily", b =>
                {
                    b.Property<int>("ThreatFamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("threat_family_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ThreatFamilyId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("ThreatClassId")
                        .HasColumnType("integer")
                        .HasColumnName("threat_class_id");

                    b.HasKey("ThreatFamilyId")
                        .HasName("pk_threat_families");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_threat_families_code");

                    b.HasIndex("ThreatClassId")
                        .HasDatabaseName("ix_threat_families_threat_class_id");

                    b.ToTable("threat_families", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatModel", b =>
                {
                    b.Property<int>("ThreatModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("threat_model_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ThreatModelId"));

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("canonical_name");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Country")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("country");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("manufacturer");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int>("ThreatFamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("threat_family_id");

                    b.HasKey("ThreatModelId")
                        .HasName("pk_threat_models");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_threat_models_code");

                    b.HasIndex("ThreatFamilyId")
                        .HasDatabaseName("ix_threat_models_threat_family_id");

                    b.ToTable("threat_models", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatModelAlias", b =>
                {
                    b.Property<int>("ThreatModelAliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("threat_model_alias_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ThreatModelAliasId"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("alias");

                    b.Property<bool>("ExactMatch")
                        .HasColumnType("boolean")
                        .HasColumnName("exact_match");

                    b.Property<int>("ImpliedConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("implied_confidence");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("target_id");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("integer")
                        .HasColumnName("target_level");

                    b.HasKey("ThreatModelAliasId")
                        .HasName("pk_threat_model_aliases");

                    b.HasIndex("Alias", "Language", "TargetLevel", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("ix_threat_model_aliases_alias_language_target_level_target_id");

                    b.ToTable("threat_model_aliases", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatTrack", b =>
                {
                    b.Property<long>("ThreatTrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("threat_track_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ThreatTrackId"));

                    b.Property<string>("ClosedReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("closed_reason");

                    b.Property<int>("DirectionConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("direction_confidence");

                    b.Property<double?>("DirectionDeg")
                        .HasColumnType("double precision")
                        .HasColumnName("direction_deg");

                    b.Property<int>("DirectionKind")
                        .HasColumnType("integer")
                        .HasColumnName("direction_kind");

                    b.Property<int>("DistinctSourceCount")
                        .HasColumnType("integer")
                        .HasColumnName("distinct_source_count");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<Geometry>("LastLocation")
                        .HasColumnType("geography (geometry, 4326)")
                        .HasColumnName("last_location");

                    b.Property<double?>("LastLocationAccuracyKm")
                        .HasColumnType("double precision")
                        .HasColumnName("last_location_accuracy_km");

                    b.Property<int>("LastLocationKind")
                        .HasColumnType("integer")
                        .HasColumnName("last_location_kind");

                    b.Property<int?>("LastLocationPlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("last_location_place_id");

                    b.Property<long?>("LastObservationId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_observation_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int?>("LastSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("last_source_id");

                    b.Property<int>("ModelConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("model_confidence");

                    b.Property<int?>("ObjectCount")
                        .HasColumnType("integer")
                        .HasColumnName("object_count");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("integer")
                        .HasColumnName("observation_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("ThreatCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("threat_category_id");

                    b.Property<int?>("ThreatClassId")
                        .HasColumnType("integer")
                        .HasColumnName("threat_class_id");

                    b.Property<int?>("ThreatFamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("threat_family_id");

                    b.Property<int?>("ThreatModelId")
                        .HasColumnType("integer")
                        .HasColumnName("threat_model_id");

                    b.Property<int>("TrackConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("track_confidence");

                    b.Property<LineString>("TrackGeometry")
                        .HasColumnType("geometry (linestring, 4326)")
                        .HasColumnName("track_geometry");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ThreatTrackId")
                        .HasName("pk_threat_tracks");

                    b.HasIndex("LastLocation")
                        .HasDatabaseName("ix_threat_tracks_last_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LastLocation"), "gist");

                    b.HasIndex("LastLocationPlaceId")
                        .HasDatabaseName("ix_threat_tracks_last_location_place_id");

                    b.HasIndex("ThreatCategoryId")
                        .HasDatabaseName("ix_threat_tracks_threat_category_id");

                    b.HasIndex("ThreatFamilyId")
                        .HasDatabaseName("ix_threat_tracks_threat_family_id");

                    b.HasIndex("ThreatModelId")
                        .HasDatabaseName("ix_threat_tracks_threat_model_id");

                    b.HasIndex("Status", "LastSeenAt")
                        .HasDatabaseName("ix_threat_tracks_status_last_seen_at");

                    b.HasIndex("ThreatClassId", "Status")
                        .HasDatabaseName("ix_threat_tracks_threat_class_id_status");

                    b.ToTable("threat_tracks", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatTrackObservation", b =>
                {
                    b.Property<long>("ThreatTrackId")
                        .HasColumnType("bigint")
                        .HasColumnName("threat_track_id");

                    b.Property<long>("ObservationId")
                        .HasColumnType("bigint")
                        .HasColumnName("observation_id");

                    b.Property<double>("AssociationConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("association_confidence");

                    b.Property<JsonDocument>("AssociationReason")
                        .HasColumnType("jsonb")
                        .HasColumnName("association_reason");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("ThreatTrackId", "ObservationId")
                        .HasName("pk_threat_track_observations");

                    b.HasIndex("ObservationId")
                        .HasDatabaseName("ix_threat_track_observations_observation_id");

                    b.ToTable("threat_track_observations", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatTrackRevision", b =>
                {
                    b.Property<long>("ThreatTrackRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("threat_track_revision_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ThreatTrackRevisionId"));

                    b.Property<int>("DirectionConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("direction_confidence");

                    b.Property<double?>("DirectionDeg")
                        .HasColumnType("double precision")
                        .HasColumnName("direction_deg");

                    b.Property<int>("DirectionKind")
                        .HasColumnType("integer")
                        .HasColumnName("direction_kind");

                    b.Property<Geometry>("LastLocation")
                        .HasColumnType("geography (geometry, 4326)")
                        .HasColumnName("last_location");

                    b.Property<double?>("LastLocationAccuracyKm")
                        .HasColumnType("double precision")
                        .HasColumnName("last_location_accuracy_km");

                    b.Property<int>("LastLocationKind")
                        .HasColumnType("integer")
                        .HasColumnName("last_location_kind");

                    b.Property<int?>("LastLocationPlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("last_location_place_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("ModelConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("model_confidence");

                    b.Property<int?>("ObjectCount")
                        .HasColumnType("integer")
                        .HasColumnName("object_count");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("integer")
                        .HasColumnName("observation_count");

                    b.Property<long?>("ObservationId")
                        .HasColumnType("bigint")
                        .HasColumnName("observation_id");

                    b.Property<DateTimeOffset>("RevisionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revision_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("ThreatCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("threat_category_id");

                    b.Property<int?>("ThreatClassId")
                        .HasColumnType("integer")
                        .HasColumnName("threat_class_id");

                    b.Property<int?>("ThreatFamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("threat_family_id");

                    b.Property<int?>("ThreatModelId")
                        .HasColumnType("integer")
                        .HasColumnName("threat_model_id");

                    b.Property<long>("ThreatTrackId")
                        .HasColumnType("bigint")
                        .HasColumnName("threat_track_id");

                    b.Property<int>("TrackConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("track_confidence");

                    b.Property<LineString>("TrackGeometry")
                        .HasColumnType("geometry (linestring, 4326)")
                        .HasColumnName("track_geometry");

                    b.HasKey("ThreatTrackRevisionId")
                        .HasName("pk_threat_track_revisions");

                    b.HasIndex("RevisionAt")
                        .HasDatabaseName("ix_threat_track_revisions_revision_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RevisionAt"), "brin");

                    b.HasIndex("ThreatTrackId", "RevisionAt")
                        .HasDatabaseName("ix_threat_track_revisions_threat_track_id_revision_at");

                    b.ToTable("threat_track_revisions", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.UserLocation", b =>
                {
                    b.Property<Guid>("UserLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_location_id");

                    b.Property<string>("ClientKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_key");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserLocationId")
                        .HasName("pk_user_locations");

                    b.HasIndex("ClientKey")
                        .IsUnique()
                        .HasDatabaseName("ix_user_locations_client_key");

                    b.ToTable("user_locations", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.AirAlert", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_air_alerts_places_place_id");

                    b.HasOne("Puluj.Domain.Entities.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_air_alerts_sources_source_id");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.CollectorState", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.Source", "Source")
                        .WithOne("CollectorState")
                        .HasForeignKey("Puluj.Domain.Entities.CollectorState", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collector_states_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.Observation", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.Place", null)
                        .WithMany()
                        .HasForeignKey("DestinationPlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_observations_places_destination_place_id");

                    b.HasOne("Puluj.Domain.Entities.Observation", null)
                        .WithMany()
                        .HasForeignKey("DuplicateOfObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_observations_observations_duplicate_of_observation_id");

                    b.HasOne("Puluj.Domain.Entities.Place", "LocationPlace")
                        .WithMany()
                        .HasForeignKey("LocationPlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_observations_places_location_place_id");

                    b.HasOne("Puluj.Domain.Entities.Place", null)
                        .WithMany()
                        .HasForeignKey("OriginPlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_observations_places_origin_place_id");

                    b.HasOne("Puluj.Domain.Entities.RawMessage", "RawMessage")
                        .WithMany("Observations")
                        .HasForeignKey("RawMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observations_raw_messages_raw_message_id");

                    b.HasOne("Puluj.Domain.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observations_sources_source_id");

                    b.HasOne("Puluj.Domain.Entities.ThreatCategory", null)
                        .WithMany()
                        .HasForeignKey("ThreatCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_observations_threat_categories_threat_category_id");

                    b.HasOne("Puluj.Domain.Entities.ThreatClass", null)
                        .WithMany()
                        .HasForeignKey("ThreatClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_observations_threat_classes_threat_class_id");

                    b.HasOne("Puluj.Domain.Entities.ThreatFamily", null)
                        .WithMany()
                        .HasForeignKey("ThreatFamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_observations_threat_families_threat_family_id");

                    b.HasOne("Puluj.Domain.Entities.ThreatModel", null)
                        .WithMany()
                        .HasForeignKey("ThreatModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_observations_threat_models_threat_model_id");

                    b.Navigation("LocationPlace");

                    b.Navigation("RawMessage");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.Place", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.Place", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_places_places_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.RawMessage", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_raw_messages_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatClass", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.ThreatCategory", "Category")
                        .WithMany("Classes")
                        .HasForeignKey("ThreatCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_threat_classes_threat_categories_threat_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatFamily", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.ThreatClass", "Class")
                        .WithMany("Families")
                        .HasForeignKey("ThreatClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_threat_families_threat_classes_threat_class_id");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatModel", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.ThreatFamily", "Family")
                        .WithMany("Models")
                        .HasForeignKey("ThreatFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_threat_models_threat_families_threat_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatTrack", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.Place", null)
                        .WithMany()
                        .HasForeignKey("LastLocationPlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_threat_tracks_places_last_location_place_id");

                    b.HasOne("Puluj.Domain.Entities.ThreatCategory", null)
                        .WithMany()
                        .HasForeignKey("ThreatCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_threat_tracks_threat_categories_threat_category_id");

                    b.HasOne("Puluj.Domain.Entities.ThreatClass", null)
                        .WithMany()
                        .HasForeignKey("ThreatClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_threat_tracks_threat_classes_threat_class_id");

                    b.HasOne("Puluj.Domain.Entities.ThreatFamily", null)
                        .WithMany()
                        .HasForeignKey("ThreatFamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_threat_tracks_threat_families_threat_family_id");

                    b.HasOne("Puluj.Domain.Entities.ThreatModel", null)
                        .WithMany()
                        .HasForeignKey("ThreatModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_threat_tracks_threat_models_threat_model_id");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatTrackObservation", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.Observation", "Observation")
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_threat_track_observations_observations_observation_id");

                    b.HasOne("Puluj.Domain.Entities.ThreatTrack", "Track")
                        .WithMany("Observations")
                        .HasForeignKey("ThreatTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_threat_track_observations_threat_tracks_threat_track_id");

                    b.Navigation("Observation");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatTrackRevision", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.ThreatTrack", "Track")
                        .WithMany()
                        .HasForeignKey("ThreatTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_threat_track_revisions_threat_tracks_threat_track_id");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.RawMessage", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.Source", b =>
                {
                    b.Navigation("CollectorState");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatCategory", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatClass", b =>
                {
                    b.Navigation("Families");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatFamily", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ThreatTrack", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
