using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore.Migrations;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Puluj.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class RenameThreatToTarget : Migration
    {
        /// <summary>
        /// Threat became Target: every table, column, index and constraint is renamed in place (generated from the model
        /// snapshot, hand-checked). The scaffolded version would have dropped and recreated the tables.
        /// </summary>
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameTable(name: "threats", newName: "targets");
            migrationBuilder.RenameTable(name: "threat_categories", newName: "target_categories");
            migrationBuilder.RenameTable(name: "threat_classes", newName: "target_classes");
            migrationBuilder.RenameTable(name: "threat_families", newName: "target_families");
            migrationBuilder.RenameTable(name: "threat_links", newName: "target_links");
            migrationBuilder.RenameTable(name: "threat_models", newName: "target_models");
            migrationBuilder.RenameTable(name: "threat_model_aliases", newName: "target_model_aliases");
            migrationBuilder.RenameTable(name: "threat_tracks", newName: "target_tracks");
            migrationBuilder.RenameTable(name: "threat_track_revisions", newName: "target_track_revisions");
            migrationBuilder.RenameTable(name: "track_threats", newName: "track_targets");
            migrationBuilder.RenameColumn(name: "threat_id", table: "targets", newName: "target_id");
            migrationBuilder.RenameColumn(name: "duplicate_of_threat_id", table: "targets", newName: "duplicate_of_target_id");
            migrationBuilder.RenameColumn(name: "threat_category_id", table: "targets", newName: "target_category_id");
            migrationBuilder.RenameColumn(name: "threat_class_id", table: "targets", newName: "target_class_id");
            migrationBuilder.RenameColumn(name: "threat_family_id", table: "targets", newName: "target_family_id");
            migrationBuilder.RenameColumn(name: "threat_model_id", table: "targets", newName: "target_model_id");
            migrationBuilder.RenameColumn(name: "threat_category_id", table: "target_categories", newName: "target_category_id");
            migrationBuilder.RenameColumn(name: "threat_class_id", table: "target_classes", newName: "target_class_id");
            migrationBuilder.RenameColumn(name: "threat_category_id", table: "target_classes", newName: "target_category_id");
            migrationBuilder.RenameColumn(name: "threat_family_id", table: "target_families", newName: "target_family_id");
            migrationBuilder.RenameColumn(name: "threat_class_id", table: "target_families", newName: "target_class_id");
            migrationBuilder.RenameColumn(name: "from_threat_id", table: "target_links", newName: "from_target_id");
            migrationBuilder.RenameColumn(name: "to_threat_id", table: "target_links", newName: "to_target_id");
            migrationBuilder.RenameColumn(name: "threat_model_id", table: "target_models", newName: "target_model_id");
            migrationBuilder.RenameColumn(name: "threat_family_id", table: "target_models", newName: "target_family_id");
            migrationBuilder.RenameColumn(name: "threat_model_alias_id", table: "target_model_aliases", newName: "target_model_alias_id");
            migrationBuilder.RenameColumn(name: "threat_track_id", table: "target_tracks", newName: "target_track_id");
            migrationBuilder.RenameColumn(name: "last_threat_id", table: "target_tracks", newName: "last_target_id");
            migrationBuilder.RenameColumn(name: "threat_category_id", table: "target_tracks", newName: "target_category_id");
            migrationBuilder.RenameColumn(name: "threat_class_id", table: "target_tracks", newName: "target_class_id");
            migrationBuilder.RenameColumn(name: "threat_count", table: "target_tracks", newName: "target_count");
            migrationBuilder.RenameColumn(name: "threat_family_id", table: "target_tracks", newName: "target_family_id");
            migrationBuilder.RenameColumn(name: "threat_model_id", table: "target_tracks", newName: "target_model_id");
            migrationBuilder.RenameColumn(name: "threat_track_revision_id", table: "target_track_revisions", newName: "target_track_revision_id");
            migrationBuilder.RenameColumn(name: "threat_category_id", table: "target_track_revisions", newName: "target_category_id");
            migrationBuilder.RenameColumn(name: "threat_class_id", table: "target_track_revisions", newName: "target_class_id");
            migrationBuilder.RenameColumn(name: "threat_count", table: "target_track_revisions", newName: "target_count");
            migrationBuilder.RenameColumn(name: "threat_family_id", table: "target_track_revisions", newName: "target_family_id");
            migrationBuilder.RenameColumn(name: "threat_id", table: "target_track_revisions", newName: "target_id");
            migrationBuilder.RenameColumn(name: "threat_model_id", table: "target_track_revisions", newName: "target_model_id");
            migrationBuilder.RenameColumn(name: "threat_track_id", table: "target_track_revisions", newName: "target_track_id");
            migrationBuilder.RenameColumn(name: "threat_track_id", table: "track_targets", newName: "target_track_id");
            migrationBuilder.RenameColumn(name: "threat_id", table: "track_targets", newName: "target_id");
            migrationBuilder.RenameIndex(name: "ix_threats_destination_place_id", table: "targets", newName: "ix_targets_destination_place_id");
            migrationBuilder.RenameIndex(name: "ix_threats_duplicate_of_threat_id", table: "targets", newName: "ix_targets_duplicate_of_target_id");
            migrationBuilder.RenameIndex(name: "ix_threats_location", table: "targets", newName: "ix_targets_location");
            migrationBuilder.RenameIndex(name: "ix_threats_location_place_id", table: "targets", newName: "ix_targets_location_place_id");
            migrationBuilder.RenameIndex(name: "ix_threats_observed_at", table: "targets", newName: "ix_targets_observed_at");
            migrationBuilder.RenameIndex(name: "ix_threats_origin_place_id", table: "targets", newName: "ix_targets_origin_place_id");
            migrationBuilder.RenameIndex(name: "ix_threats_raw_message_id", table: "targets", newName: "ix_targets_raw_message_id");
            migrationBuilder.RenameIndex(name: "ix_threats_source_id", table: "targets", newName: "ix_targets_source_id");
            migrationBuilder.RenameIndex(name: "ix_threats_threat_category_id", table: "targets", newName: "ix_targets_target_category_id");
            migrationBuilder.RenameIndex(name: "ix_threats_threat_family_id", table: "targets", newName: "ix_targets_target_family_id");
            migrationBuilder.RenameIndex(name: "ix_threats_threat_model_id", table: "targets", newName: "ix_targets_target_model_id");
            migrationBuilder.RenameIndex(name: "ix_threats_threat_class_id_observed_at", table: "targets", newName: "ix_targets_target_class_id_observed_at");
            migrationBuilder.RenameIndex(name: "ix_threat_categories_code", table: "target_categories", newName: "ix_target_categories_code");
            migrationBuilder.RenameIndex(name: "ix_threat_classes_code", table: "target_classes", newName: "ix_target_classes_code");
            migrationBuilder.RenameIndex(name: "ix_threat_classes_threat_category_id", table: "target_classes", newName: "ix_target_classes_target_category_id");
            migrationBuilder.RenameIndex(name: "ix_threat_families_code", table: "target_families", newName: "ix_target_families_code");
            migrationBuilder.RenameIndex(name: "ix_threat_families_threat_class_id", table: "target_families", newName: "ix_target_families_target_class_id");
            migrationBuilder.RenameIndex(name: "ix_threat_links_created_at", table: "target_links", newName: "ix_target_links_created_at");
            migrationBuilder.RenameIndex(name: "ix_threat_links_to_threat_id", table: "target_links", newName: "ix_target_links_to_target_id");
            migrationBuilder.RenameIndex(name: "ix_threat_models_code", table: "target_models", newName: "ix_target_models_code");
            migrationBuilder.RenameIndex(name: "ix_threat_models_threat_family_id", table: "target_models", newName: "ix_target_models_target_family_id");
            migrationBuilder.RenameIndex(name: "ix_threat_model_aliases_alias_language_target_level_target_id", table: "target_model_aliases", newName: "ix_target_model_aliases_alias_language_target_level_target_id");
            migrationBuilder.RenameIndex(name: "ix_threat_tracks_last_location", table: "target_tracks", newName: "ix_target_tracks_last_location");
            migrationBuilder.RenameIndex(name: "ix_threat_tracks_last_location_place_id", table: "target_tracks", newName: "ix_target_tracks_last_location_place_id");
            migrationBuilder.RenameIndex(name: "ix_threat_tracks_threat_category_id", table: "target_tracks", newName: "ix_target_tracks_target_category_id");
            migrationBuilder.RenameIndex(name: "ix_threat_tracks_threat_family_id", table: "target_tracks", newName: "ix_target_tracks_target_family_id");
            migrationBuilder.RenameIndex(name: "ix_threat_tracks_threat_model_id", table: "target_tracks", newName: "ix_target_tracks_target_model_id");
            migrationBuilder.RenameIndex(name: "ix_threat_tracks_status_last_seen_at", table: "target_tracks", newName: "ix_target_tracks_status_last_seen_at");
            migrationBuilder.RenameIndex(name: "ix_threat_tracks_threat_class_id_status", table: "target_tracks", newName: "ix_target_tracks_target_class_id_status");
            migrationBuilder.RenameIndex(name: "ix_threat_track_revisions_revision_at", table: "target_track_revisions", newName: "ix_target_track_revisions_revision_at");
            migrationBuilder.RenameIndex(name: "ix_threat_track_revisions_threat_track_id_revision_at", table: "target_track_revisions", newName: "ix_target_track_revisions_target_track_id_revision_at");
            migrationBuilder.RenameIndex(name: "ix_track_threats_threat_id", table: "track_targets", newName: "ix_track_targets_target_id");
            migrationBuilder.Sql("ALTER TABLE targets RENAME CONSTRAINT pk_threats TO pk_targets;");
            migrationBuilder.Sql("ALTER TABLE targets RENAME CONSTRAINT fk_threats_places_destination_place_id TO fk_targets_places_destination_place_id;");
            migrationBuilder.Sql("ALTER TABLE targets RENAME CONSTRAINT fk_threats_threats_duplicate_of_threat_id TO fk_targets_targets_duplicate_of_target_id;");
            migrationBuilder.Sql("ALTER TABLE targets RENAME CONSTRAINT fk_threats_places_location_place_id TO fk_targets_places_location_place_id;");
            migrationBuilder.Sql("ALTER TABLE targets RENAME CONSTRAINT fk_threats_places_origin_place_id TO fk_targets_places_origin_place_id;");
            migrationBuilder.Sql("ALTER TABLE targets RENAME CONSTRAINT fk_threats_raw_messages_raw_message_id TO fk_targets_raw_messages_raw_message_id;");
            migrationBuilder.Sql("ALTER TABLE targets RENAME CONSTRAINT fk_threats_sources_source_id TO fk_targets_sources_source_id;");
            migrationBuilder.Sql("ALTER TABLE targets RENAME CONSTRAINT fk_threats_threat_categories_threat_category_id TO fk_targets_target_categories_target_category_id;");
            migrationBuilder.Sql("ALTER TABLE targets RENAME CONSTRAINT fk_threats_threat_classes_threat_class_id TO fk_targets_target_classes_target_class_id;");
            migrationBuilder.Sql("ALTER TABLE targets RENAME CONSTRAINT fk_threats_threat_families_threat_family_id TO fk_targets_target_families_target_family_id;");
            migrationBuilder.Sql("ALTER TABLE targets RENAME CONSTRAINT fk_threats_threat_models_threat_model_id TO fk_targets_target_models_target_model_id;");
            migrationBuilder.Sql("ALTER TABLE target_categories RENAME CONSTRAINT pk_threat_categories TO pk_target_categories;");
            migrationBuilder.Sql("ALTER TABLE target_classes RENAME CONSTRAINT pk_threat_classes TO pk_target_classes;");
            migrationBuilder.Sql("ALTER TABLE target_classes RENAME CONSTRAINT fk_threat_classes_threat_categories_threat_category_id TO fk_target_classes_target_categories_target_category_id;");
            migrationBuilder.Sql("ALTER TABLE target_families RENAME CONSTRAINT pk_threat_families TO pk_target_families;");
            migrationBuilder.Sql("ALTER TABLE target_families RENAME CONSTRAINT fk_threat_families_threat_classes_threat_class_id TO fk_target_families_target_classes_target_class_id;");
            migrationBuilder.Sql("ALTER TABLE target_links RENAME CONSTRAINT pk_threat_links TO pk_target_links;");
            migrationBuilder.Sql("ALTER TABLE target_links RENAME CONSTRAINT fk_threat_links_threats_from_threat_id TO fk_target_links_targets_from_target_id;");
            migrationBuilder.Sql("ALTER TABLE target_links RENAME CONSTRAINT fk_threat_links_threats_to_threat_id TO fk_target_links_targets_to_target_id;");
            migrationBuilder.Sql("ALTER TABLE target_models RENAME CONSTRAINT pk_threat_models TO pk_target_models;");
            migrationBuilder.Sql("ALTER TABLE target_models RENAME CONSTRAINT fk_threat_models_threat_families_threat_family_id TO fk_target_models_target_families_target_family_id;");
            migrationBuilder.Sql("ALTER TABLE target_model_aliases RENAME CONSTRAINT pk_threat_model_aliases TO pk_target_model_aliases;");
            migrationBuilder.Sql("ALTER TABLE target_tracks RENAME CONSTRAINT pk_threat_tracks TO pk_target_tracks;");
            migrationBuilder.Sql("ALTER TABLE target_tracks RENAME CONSTRAINT fk_threat_tracks_places_last_location_place_id TO fk_target_tracks_places_last_location_place_id;");
            migrationBuilder.Sql("ALTER TABLE target_tracks RENAME CONSTRAINT fk_threat_tracks_threat_categories_threat_category_id TO fk_target_tracks_target_categories_target_category_id;");
            migrationBuilder.Sql("ALTER TABLE target_tracks RENAME CONSTRAINT fk_threat_tracks_threat_classes_threat_class_id TO fk_target_tracks_target_classes_target_class_id;");
            migrationBuilder.Sql("ALTER TABLE target_tracks RENAME CONSTRAINT fk_threat_tracks_threat_families_threat_family_id TO fk_target_tracks_target_families_target_family_id;");
            migrationBuilder.Sql("ALTER TABLE target_tracks RENAME CONSTRAINT fk_threat_tracks_threat_models_threat_model_id TO fk_target_tracks_target_models_target_model_id;");
            migrationBuilder.Sql("ALTER TABLE target_track_revisions RENAME CONSTRAINT pk_threat_track_revisions TO pk_target_track_revisions;");
            migrationBuilder.Sql("ALTER TABLE target_track_revisions RENAME CONSTRAINT fk_threat_track_revisions_threat_tracks_threat_track_id TO fk_target_track_revisions_target_tracks_target_track_id;");
            migrationBuilder.Sql("ALTER TABLE track_targets RENAME CONSTRAINT pk_track_threats TO pk_track_targets;");
            migrationBuilder.Sql("ALTER TABLE track_targets RENAME CONSTRAINT fk_track_threats_threats_threat_id TO fk_track_targets_targets_target_id;");
            migrationBuilder.Sql("ALTER TABLE track_targets RENAME CONSTRAINT fk_track_threats_threat_tracks_threat_track_id TO fk_track_targets_target_tracks_target_track_id;");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE track_threats RENAME CONSTRAINT fk_track_targets_target_tracks_target_track_id TO fk_track_threats_threat_tracks_threat_track_id;");
            migrationBuilder.Sql("ALTER TABLE track_threats RENAME CONSTRAINT fk_track_targets_targets_target_id TO fk_track_threats_threats_threat_id;");
            migrationBuilder.Sql("ALTER TABLE track_threats RENAME CONSTRAINT pk_track_targets TO pk_track_threats;");
            migrationBuilder.Sql("ALTER TABLE threat_track_revisions RENAME CONSTRAINT fk_target_track_revisions_target_tracks_target_track_id TO fk_threat_track_revisions_threat_tracks_threat_track_id;");
            migrationBuilder.Sql("ALTER TABLE threat_track_revisions RENAME CONSTRAINT pk_target_track_revisions TO pk_threat_track_revisions;");
            migrationBuilder.Sql("ALTER TABLE threat_tracks RENAME CONSTRAINT fk_target_tracks_target_models_target_model_id TO fk_threat_tracks_threat_models_threat_model_id;");
            migrationBuilder.Sql("ALTER TABLE threat_tracks RENAME CONSTRAINT fk_target_tracks_target_families_target_family_id TO fk_threat_tracks_threat_families_threat_family_id;");
            migrationBuilder.Sql("ALTER TABLE threat_tracks RENAME CONSTRAINT fk_target_tracks_target_classes_target_class_id TO fk_threat_tracks_threat_classes_threat_class_id;");
            migrationBuilder.Sql("ALTER TABLE threat_tracks RENAME CONSTRAINT fk_target_tracks_target_categories_target_category_id TO fk_threat_tracks_threat_categories_threat_category_id;");
            migrationBuilder.Sql("ALTER TABLE threat_tracks RENAME CONSTRAINT fk_target_tracks_places_last_location_place_id TO fk_threat_tracks_places_last_location_place_id;");
            migrationBuilder.Sql("ALTER TABLE threat_tracks RENAME CONSTRAINT pk_target_tracks TO pk_threat_tracks;");
            migrationBuilder.Sql("ALTER TABLE threat_model_aliases RENAME CONSTRAINT pk_target_model_aliases TO pk_threat_model_aliases;");
            migrationBuilder.Sql("ALTER TABLE threat_models RENAME CONSTRAINT fk_target_models_target_families_target_family_id TO fk_threat_models_threat_families_threat_family_id;");
            migrationBuilder.Sql("ALTER TABLE threat_models RENAME CONSTRAINT pk_target_models TO pk_threat_models;");
            migrationBuilder.Sql("ALTER TABLE threat_links RENAME CONSTRAINT fk_target_links_targets_to_target_id TO fk_threat_links_threats_to_threat_id;");
            migrationBuilder.Sql("ALTER TABLE threat_links RENAME CONSTRAINT fk_target_links_targets_from_target_id TO fk_threat_links_threats_from_threat_id;");
            migrationBuilder.Sql("ALTER TABLE threat_links RENAME CONSTRAINT pk_target_links TO pk_threat_links;");
            migrationBuilder.Sql("ALTER TABLE threat_families RENAME CONSTRAINT fk_target_families_target_classes_target_class_id TO fk_threat_families_threat_classes_threat_class_id;");
            migrationBuilder.Sql("ALTER TABLE threat_families RENAME CONSTRAINT pk_target_families TO pk_threat_families;");
            migrationBuilder.Sql("ALTER TABLE threat_classes RENAME CONSTRAINT fk_target_classes_target_categories_target_category_id TO fk_threat_classes_threat_categories_threat_category_id;");
            migrationBuilder.Sql("ALTER TABLE threat_classes RENAME CONSTRAINT pk_target_classes TO pk_threat_classes;");
            migrationBuilder.Sql("ALTER TABLE threat_categories RENAME CONSTRAINT pk_target_categories TO pk_threat_categories;");
            migrationBuilder.Sql("ALTER TABLE threats RENAME CONSTRAINT fk_targets_target_models_target_model_id TO fk_threats_threat_models_threat_model_id;");
            migrationBuilder.Sql("ALTER TABLE threats RENAME CONSTRAINT fk_targets_target_families_target_family_id TO fk_threats_threat_families_threat_family_id;");
            migrationBuilder.Sql("ALTER TABLE threats RENAME CONSTRAINT fk_targets_target_classes_target_class_id TO fk_threats_threat_classes_threat_class_id;");
            migrationBuilder.Sql("ALTER TABLE threats RENAME CONSTRAINT fk_targets_target_categories_target_category_id TO fk_threats_threat_categories_threat_category_id;");
            migrationBuilder.Sql("ALTER TABLE threats RENAME CONSTRAINT fk_targets_sources_source_id TO fk_threats_sources_source_id;");
            migrationBuilder.Sql("ALTER TABLE threats RENAME CONSTRAINT fk_targets_raw_messages_raw_message_id TO fk_threats_raw_messages_raw_message_id;");
            migrationBuilder.Sql("ALTER TABLE threats RENAME CONSTRAINT fk_targets_places_origin_place_id TO fk_threats_places_origin_place_id;");
            migrationBuilder.Sql("ALTER TABLE threats RENAME CONSTRAINT fk_targets_places_location_place_id TO fk_threats_places_location_place_id;");
            migrationBuilder.Sql("ALTER TABLE threats RENAME CONSTRAINT fk_targets_targets_duplicate_of_target_id TO fk_threats_threats_duplicate_of_threat_id;");
            migrationBuilder.Sql("ALTER TABLE threats RENAME CONSTRAINT fk_targets_places_destination_place_id TO fk_threats_places_destination_place_id;");
            migrationBuilder.Sql("ALTER TABLE threats RENAME CONSTRAINT pk_targets TO pk_threats;");
            migrationBuilder.RenameIndex(name: "ix_track_targets_target_id", table: "track_threats", newName: "ix_track_threats_threat_id");
            migrationBuilder.RenameIndex(name: "ix_target_track_revisions_target_track_id_revision_at", table: "threat_track_revisions", newName: "ix_threat_track_revisions_threat_track_id_revision_at");
            migrationBuilder.RenameIndex(name: "ix_target_track_revisions_revision_at", table: "threat_track_revisions", newName: "ix_threat_track_revisions_revision_at");
            migrationBuilder.RenameIndex(name: "ix_target_tracks_target_class_id_status", table: "threat_tracks", newName: "ix_threat_tracks_threat_class_id_status");
            migrationBuilder.RenameIndex(name: "ix_target_tracks_status_last_seen_at", table: "threat_tracks", newName: "ix_threat_tracks_status_last_seen_at");
            migrationBuilder.RenameIndex(name: "ix_target_tracks_target_model_id", table: "threat_tracks", newName: "ix_threat_tracks_threat_model_id");
            migrationBuilder.RenameIndex(name: "ix_target_tracks_target_family_id", table: "threat_tracks", newName: "ix_threat_tracks_threat_family_id");
            migrationBuilder.RenameIndex(name: "ix_target_tracks_target_category_id", table: "threat_tracks", newName: "ix_threat_tracks_threat_category_id");
            migrationBuilder.RenameIndex(name: "ix_target_tracks_last_location_place_id", table: "threat_tracks", newName: "ix_threat_tracks_last_location_place_id");
            migrationBuilder.RenameIndex(name: "ix_target_tracks_last_location", table: "threat_tracks", newName: "ix_threat_tracks_last_location");
            migrationBuilder.RenameIndex(name: "ix_target_model_aliases_alias_language_target_level_target_id", table: "threat_model_aliases", newName: "ix_threat_model_aliases_alias_language_target_level_target_id");
            migrationBuilder.RenameIndex(name: "ix_target_models_target_family_id", table: "threat_models", newName: "ix_threat_models_threat_family_id");
            migrationBuilder.RenameIndex(name: "ix_target_models_code", table: "threat_models", newName: "ix_threat_models_code");
            migrationBuilder.RenameIndex(name: "ix_target_links_to_target_id", table: "threat_links", newName: "ix_threat_links_to_threat_id");
            migrationBuilder.RenameIndex(name: "ix_target_links_created_at", table: "threat_links", newName: "ix_threat_links_created_at");
            migrationBuilder.RenameIndex(name: "ix_target_families_target_class_id", table: "threat_families", newName: "ix_threat_families_threat_class_id");
            migrationBuilder.RenameIndex(name: "ix_target_families_code", table: "threat_families", newName: "ix_threat_families_code");
            migrationBuilder.RenameIndex(name: "ix_target_classes_target_category_id", table: "threat_classes", newName: "ix_threat_classes_threat_category_id");
            migrationBuilder.RenameIndex(name: "ix_target_classes_code", table: "threat_classes", newName: "ix_threat_classes_code");
            migrationBuilder.RenameIndex(name: "ix_target_categories_code", table: "threat_categories", newName: "ix_threat_categories_code");
            migrationBuilder.RenameIndex(name: "ix_targets_target_class_id_observed_at", table: "threats", newName: "ix_threats_threat_class_id_observed_at");
            migrationBuilder.RenameIndex(name: "ix_targets_target_model_id", table: "threats", newName: "ix_threats_threat_model_id");
            migrationBuilder.RenameIndex(name: "ix_targets_target_family_id", table: "threats", newName: "ix_threats_threat_family_id");
            migrationBuilder.RenameIndex(name: "ix_targets_target_category_id", table: "threats", newName: "ix_threats_threat_category_id");
            migrationBuilder.RenameIndex(name: "ix_targets_source_id", table: "threats", newName: "ix_threats_source_id");
            migrationBuilder.RenameIndex(name: "ix_targets_raw_message_id", table: "threats", newName: "ix_threats_raw_message_id");
            migrationBuilder.RenameIndex(name: "ix_targets_origin_place_id", table: "threats", newName: "ix_threats_origin_place_id");
            migrationBuilder.RenameIndex(name: "ix_targets_observed_at", table: "threats", newName: "ix_threats_observed_at");
            migrationBuilder.RenameIndex(name: "ix_targets_location_place_id", table: "threats", newName: "ix_threats_location_place_id");
            migrationBuilder.RenameIndex(name: "ix_targets_location", table: "threats", newName: "ix_threats_location");
            migrationBuilder.RenameIndex(name: "ix_targets_duplicate_of_target_id", table: "threats", newName: "ix_threats_duplicate_of_threat_id");
            migrationBuilder.RenameIndex(name: "ix_targets_destination_place_id", table: "threats", newName: "ix_threats_destination_place_id");
            migrationBuilder.RenameColumn(name: "target_id", table: "track_threats", newName: "threat_id");
            migrationBuilder.RenameColumn(name: "target_track_id", table: "track_threats", newName: "threat_track_id");
            migrationBuilder.RenameColumn(name: "target_track_id", table: "threat_track_revisions", newName: "threat_track_id");
            migrationBuilder.RenameColumn(name: "target_model_id", table: "threat_track_revisions", newName: "threat_model_id");
            migrationBuilder.RenameColumn(name: "target_id", table: "threat_track_revisions", newName: "threat_id");
            migrationBuilder.RenameColumn(name: "target_family_id", table: "threat_track_revisions", newName: "threat_family_id");
            migrationBuilder.RenameColumn(name: "target_count", table: "threat_track_revisions", newName: "threat_count");
            migrationBuilder.RenameColumn(name: "target_class_id", table: "threat_track_revisions", newName: "threat_class_id");
            migrationBuilder.RenameColumn(name: "target_category_id", table: "threat_track_revisions", newName: "threat_category_id");
            migrationBuilder.RenameColumn(name: "target_track_revision_id", table: "threat_track_revisions", newName: "threat_track_revision_id");
            migrationBuilder.RenameColumn(name: "target_model_id", table: "threat_tracks", newName: "threat_model_id");
            migrationBuilder.RenameColumn(name: "target_family_id", table: "threat_tracks", newName: "threat_family_id");
            migrationBuilder.RenameColumn(name: "target_count", table: "threat_tracks", newName: "threat_count");
            migrationBuilder.RenameColumn(name: "target_class_id", table: "threat_tracks", newName: "threat_class_id");
            migrationBuilder.RenameColumn(name: "target_category_id", table: "threat_tracks", newName: "threat_category_id");
            migrationBuilder.RenameColumn(name: "last_target_id", table: "threat_tracks", newName: "last_threat_id");
            migrationBuilder.RenameColumn(name: "target_track_id", table: "threat_tracks", newName: "threat_track_id");
            migrationBuilder.RenameColumn(name: "target_model_alias_id", table: "threat_model_aliases", newName: "threat_model_alias_id");
            migrationBuilder.RenameColumn(name: "target_family_id", table: "threat_models", newName: "threat_family_id");
            migrationBuilder.RenameColumn(name: "target_model_id", table: "threat_models", newName: "threat_model_id");
            migrationBuilder.RenameColumn(name: "to_target_id", table: "threat_links", newName: "to_threat_id");
            migrationBuilder.RenameColumn(name: "from_target_id", table: "threat_links", newName: "from_threat_id");
            migrationBuilder.RenameColumn(name: "target_class_id", table: "threat_families", newName: "threat_class_id");
            migrationBuilder.RenameColumn(name: "target_family_id", table: "threat_families", newName: "threat_family_id");
            migrationBuilder.RenameColumn(name: "target_category_id", table: "threat_classes", newName: "threat_category_id");
            migrationBuilder.RenameColumn(name: "target_class_id", table: "threat_classes", newName: "threat_class_id");
            migrationBuilder.RenameColumn(name: "target_category_id", table: "threat_categories", newName: "threat_category_id");
            migrationBuilder.RenameColumn(name: "target_model_id", table: "threats", newName: "threat_model_id");
            migrationBuilder.RenameColumn(name: "target_family_id", table: "threats", newName: "threat_family_id");
            migrationBuilder.RenameColumn(name: "target_class_id", table: "threats", newName: "threat_class_id");
            migrationBuilder.RenameColumn(name: "target_category_id", table: "threats", newName: "threat_category_id");
            migrationBuilder.RenameColumn(name: "duplicate_of_target_id", table: "threats", newName: "duplicate_of_threat_id");
            migrationBuilder.RenameColumn(name: "target_id", table: "threats", newName: "threat_id");
            migrationBuilder.RenameTable(name: "track_targets", newName: "track_threats");
            migrationBuilder.RenameTable(name: "target_track_revisions", newName: "threat_track_revisions");
            migrationBuilder.RenameTable(name: "target_tracks", newName: "threat_tracks");
            migrationBuilder.RenameTable(name: "target_model_aliases", newName: "threat_model_aliases");
            migrationBuilder.RenameTable(name: "target_models", newName: "threat_models");
            migrationBuilder.RenameTable(name: "target_links", newName: "threat_links");
            migrationBuilder.RenameTable(name: "target_families", newName: "threat_families");
            migrationBuilder.RenameTable(name: "target_classes", newName: "threat_classes");
            migrationBuilder.RenameTable(name: "target_categories", newName: "threat_categories");
            migrationBuilder.RenameTable(name: "targets", newName: "threats");
        }
    }
}
